%------------------------------------------------------------------------------
% File     : CSR111+3 : TPTP v8.1.2. Released v3.5.0.
% Domain   : Common Sense Reasoning
% Problem  : 8005 axioms from Cyc
% Version  : Especial.
% English  :

% Refs     : [RS+]   Reagan Smith et al., The Cyc TPTP Challenge Problem
% Source   : [RS+]
% Names    :

% Status   : Satisfiable
% Rating   : 0.67 v6.4.0, 1.00 v3.5.0
% Syntax   : Number of formulae    : 8005 (3281 unt;   0 def)
%            Number of atoms       : 13034 (   0 equ)
%            Maximal formula atoms :    3 (   1 avg)
%            Number of connectives : 5103 (  74   ~;   0   |; 347   &)
%                                         (   0 <=>;4682  =>;   0  <=;   0 <~>)
%            Maximal formula depth :    7 (   2 avg)
%            Maximal term depth    :    6 (   1 avg)
%            Number of predicates  : 1520 (1520 usr;   0 prp; 1-5 aty)
%            Number of functors    : 3266 (3266 usr;3136 con; 0-4 aty)
%            Number of variables   : 5970 (5970   !;   0   ?)
% SPC      : FOF_SAT_RFO_NEQ

% Comments : Autogenerated from the OpenCyc KB. Documentation can be found at
%            http://opencyc.org/doc/#TPTP_Challenge_Problem_Set
%          : Cyc(R) Knowledge Base Copyright(C) 1995-2007 Cycorp, Inc., Austin,
%            TX, USA. All rights reserved.
%          : OpenCyc Knowledge Base Copyright(C) 2001-2007 Cycorp, Inc.,
%            Austin, TX, USA. All rights reserved.
%          : A superset of CSR002+0.ax CSR002+1.ax
%          : It is known that there are some duplicate axioms.
%------------------------------------------------------------------------------
include('Axioms/CSR002+2.ax').
%------------------------------------------------------------------------------
