%------------------------------------------------------------------------------
% File     : CSR111+2 : TPTP v8.1.2. Released v3.5.0.
% Domain   : Common Sense Reasoning
% Problem  : 1131 axioms from Cyc
% Version  : Especial.
% English  :

% Refs     : [RS+]   Reagan Smith et al., The Cyc TPTP Challenge Problem
% Source   : [RS+]
% Names    :

% Status   : Satisfiable
% Rating   : 0.33 v7.1.0, 0.00 v6.2.0, 0.20 v6.0.0, 0.00 v5.4.0, 0.57 v5.3.0, 0.71 v5.2.0, 0.50 v5.0.0, 0.33 v4.1.0, 0.50 v4.0.1, 0.67 v3.5.0
% Syntax   : Number of formulae    : 1131 ( 346 unt;   0 def)
%            Number of atoms       : 1964 (   0 equ)
%            Maximal formula atoms :    3 (   1 avg)
%            Number of connectives :  842 (   9   ~;   0   |;  54   &)
%                                         (   0 <=>; 779  =>;   0  <=;   0 <~>)
%            Maximal formula depth :    7 (   3 avg)
%            Maximal term depth    :    4 (   1 avg)
%            Number of predicates  :  269 ( 269 usr;   0 prp; 1-3 aty)
%            Number of functors    :  413 ( 413 usr; 396 con; 0-4 aty)
%            Number of variables   : 1121 (1121   !;   0   ?)
% SPC      : FOF_SAT_RFO_NEQ

% Comments : Autogenerated from the OpenCyc KB. Documentation can be found at
%            http://opencyc.org/doc/#TPTP_Challenge_Problem_Set
%          : Cyc(R) Knowledge Base Copyright(C) 1995-2007 Cycorp, Inc., Austin,
%            TX, USA. All rights reserved.
%          : OpenCyc Knowledge Base Copyright(C) 2001-2007 Cycorp, Inc.,
%            Austin, TX, USA. All rights reserved.
%------------------------------------------------------------------------------
include('Axioms/CSR002+1.ax').
%------------------------------------------------------------------------------
