%------------------------------------------------------------------------------
% File     : CSR111+4 : TPTP v8.1.2. Released v3.5.0.
% Domain   : Common Sense Reasoning
% Problem  : 44216 axioms from Cyc
% Version  : Especial.
% English  :

% Refs     : [RS+]   Reagan Smith et al., The Cyc TPTP Challenge Problem
% Source   : [RS+]
% Names    :

% Status   : Satisfiable
% Rating   : 1.00 v3.5.0
% Syntax   : Number of formulae    : 44216 (23808 unt;   0 def)
%            Number of atoms       : 65453 (   8 equ)
%            Maximal formula atoms :    4 (   1 avg)
%            Number of connectives : 21419 ( 182   ~;   0   |; 913   &)
%                                         (   0 <=>;20324  =>;   0  <=;   0 <~>)
%            Maximal formula depth :    8 (   2 avg)
%            Maximal term depth    :    6 (   1 avg)
%            Number of predicates  : 6814 (6813 usr;   0 prp; 1-6 aty)
%            Number of functors    : 15051 (15051 usr;14712 con; 0-4 aty)
%            Number of variables   : 24045 (24045   !;   0   ?)
% SPC      : FOF_SAT_RFO_SEQ

% Comments : Autogenerated from the OpenCyc KB. Documentation can be found at
%            http://opencyc.org/doc/#TPTP_Challenge_Problem_Set
%          : Cyc(R) Knowledge Base Copyright(C) 1995-2007 Cycorp, Inc., Austin,
%            TX, USA. All rights reserved.
%          : OpenCyc Knowledge Base Copyright(C) 2001-2007 Cycorp, Inc.,
%            Austin, TX, USA. All rights reserved.
%          : A superset of CSR002+0.ax CSR002+1.ax CSR002+2
%          : It is known that there are some duplicate axioms.
%------------------------------------------------------------------------------
include('Axioms/CSR002+3.ax').
%------------------------------------------------------------------------------
