%------------------------------------------------------------------------------
% File     : CSR111+5 : TPTP v8.1.2. Bugfixed v5.5.0.
% Domain   : Common Sense Reasoning
% Problem  : 540294 axioms from Cyc
% Version  : Especial.
% English  :

% Refs     : [RS+]   Reagan Smith et al., The Cyc TPTP Challenge Problem
% Source   : [RS+]
% Names    :

% Status   : Satisfiable
% Rating   : 1.00 v5.5.0
% Syntax   : Number of formulae    : 540249 (168243 unt;   0 def)
%            Number of atoms       : 920067 (  24 equ)
%            Maximal formula atoms :    4 (   1 avg)
%            Number of connectives : 389469 (9651   ~;   0   |;15895   &)
%                                         (   0 <=>;363923  =>;   0  <=;   0 <~>)
%            Maximal formula depth :   10 (   2 avg)
%            Maximal term depth    :    8 (   1 avg)
%            Number of predicates  : 103247 (103246 usr;   0 prp; 1-7 aty)
%            Number of functors    : 255473 (255473 usr;253178 con; 0-5 aty)
%            Number of variables   : 326597 (326597   !;   0   ?)
% SPC      : FOF_UNS_RFO_SEQ

% Comments : Autogenerated from the OpenCyc KB. Documentation can be found at
%            http://opencyc.org/doc/#TPTP_Challenge_Problem_Set
%          : Cyc(R) Knowledge Base Copyright(C) 1995-2007 Cycorp, Inc., Austin,
%            TX, USA. All rights reserved.
%          : OpenCyc Knowledge Base Copyright(C) 2001-2007 Cycorp, Inc.,
%            Austin, TX, USA. All rights reserved.
%          : A superset of CSR002+0.ax CSR002+1.ax CSR002+2 CSR002+3
%          : It is known that there are some duplicate axioms.
% Bugfixes : v5.5.0 - Bugfix in CSR002+4.ax
%------------------------------------------------------------------------------
include('Axioms/CSR002+4.ax').
%------------------------------------------------------------------------------
