%------------------------------------------------------------------------------
% File     : NUM574+3 : TPTP v8.1.0. Released v4.0.0.
% Domain   : Number Theory
% Problem  : Ramsey's Infinite Theorem 15_02_04_02, 02 expansion
% Version  : Especial.
% English  :

% Refs     : [VLP07] Verchinine et al. (2007), System for Automated Deduction
%          : [Pas08] Paskevich (2008), Email to G. Sutcliffe
% Source   : [Pas08]
% Names    : ramsey_15_02_04_02.02 [Pas08]

% Status   : Theorem
% Rating   : 0.50 v8.1.0, 0.47 v7.5.0, 0.50 v7.4.0, 0.37 v7.3.0, 0.48 v7.2.0, 0.45 v7.1.0, 0.48 v7.0.0, 0.37 v6.4.0, 0.46 v6.3.0, 0.38 v6.2.0, 0.36 v6.1.0, 0.47 v6.0.0, 0.43 v5.5.0, 0.63 v5.4.0, 0.61 v5.3.0, 0.67 v5.2.0, 0.50 v5.1.0, 0.67 v5.0.0, 0.79 v4.1.0, 0.87 v4.0.1, 0.91 v4.0.0
% Syntax   : Number of formulae    :   86 (   6 unt;  11 def)
%            Number of atoms       :  411 (  64 equ)
%            Maximal formula atoms :   41 (   4 avg)
%            Number of connectives :  348 (  23   ~;  13   |; 143   &)
%                                         (  25 <=>; 144  =>;   0  <=;   0 <~>)
%            Maximal formula depth :   23 (   6 avg)
%            Maximal term depth    :    4 (   1 avg)
%            Number of predicates  :   11 (   9 usr;   1 prp; 0-2 aty)
%            Number of functors    :   25 (  25 usr;  11 con; 0-2 aty)
%            Number of variables   :  174 ( 163   !;  11   ?)
% SPC      : FOF_THM_RFO_SEQ

% Comments : Problem generated by the SAD system [VLP07]
%------------------------------------------------------------------------------
fof(mSetSort,axiom,
    ! [W0] :
      ( aSet0(W0)
     => $true ) ).

fof(mElmSort,axiom,
    ! [W0] :
      ( aElement0(W0)
     => $true ) ).

fof(mEOfElem,axiom,
    ! [W0] :
      ( aSet0(W0)
     => ! [W1] :
          ( aElementOf0(W1,W0)
         => aElement0(W1) ) ) ).

fof(mFinRel,axiom,
    ! [W0] :
      ( aSet0(W0)
     => ( isFinite0(W0)
       => $true ) ) ).

fof(mDefEmp,definition,
    ! [W0] :
      ( W0 = slcrc0
    <=> ( aSet0(W0)
        & ~ ? [W1] : aElementOf0(W1,W0) ) ) ).

fof(mEmpFin,axiom,
    isFinite0(slcrc0) ).

fof(mCntRel,axiom,
    ! [W0] :
      ( aSet0(W0)
     => ( isCountable0(W0)
       => $true ) ) ).

fof(mCountNFin,axiom,
    ! [W0] :
      ( ( aSet0(W0)
        & isCountable0(W0) )
     => ~ isFinite0(W0) ) ).

fof(mCountNFin_01,axiom,
    ! [W0] :
      ( ( aSet0(W0)
        & isCountable0(W0) )
     => W0 != slcrc0 ) ).

fof(mDefSub,definition,
    ! [W0] :
      ( aSet0(W0)
     => ! [W1] :
          ( aSubsetOf0(W1,W0)
        <=> ( aSet0(W1)
            & ! [W2] :
                ( aElementOf0(W2,W1)
               => aElementOf0(W2,W0) ) ) ) ) ).

fof(mSubFSet,axiom,
    ! [W0] :
      ( ( aSet0(W0)
        & isFinite0(W0) )
     => ! [W1] :
          ( aSubsetOf0(W1,W0)
         => isFinite0(W1) ) ) ).

fof(mSubRefl,axiom,
    ! [W0] :
      ( aSet0(W0)
     => aSubsetOf0(W0,W0) ) ).

fof(mSubASymm,axiom,
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aSet0(W1) )
     => ( ( aSubsetOf0(W0,W1)
          & aSubsetOf0(W1,W0) )
       => W0 = W1 ) ) ).

fof(mSubTrans,axiom,
    ! [W0,W1,W2] :
      ( ( aSet0(W0)
        & aSet0(W1)
        & aSet0(W2) )
     => ( ( aSubsetOf0(W0,W1)
          & aSubsetOf0(W1,W2) )
       => aSubsetOf0(W0,W2) ) ) ).

fof(mDefCons,definition,
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aElement0(W1) )
     => ! [W2] :
          ( W2 = sdtpldt0(W0,W1)
        <=> ( aSet0(W2)
            & ! [W3] :
                ( aElementOf0(W3,W2)
              <=> ( aElement0(W3)
                  & ( aElementOf0(W3,W0)
                    | W3 = W1 ) ) ) ) ) ) ).

fof(mDefDiff,definition,
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aElement0(W1) )
     => ! [W2] :
          ( W2 = sdtmndt0(W0,W1)
        <=> ( aSet0(W2)
            & ! [W3] :
                ( aElementOf0(W3,W2)
              <=> ( aElement0(W3)
                  & aElementOf0(W3,W0)
                  & W3 != W1 ) ) ) ) ) ).

fof(mConsDiff,axiom,
    ! [W0] :
      ( aSet0(W0)
     => ! [W1] :
          ( aElementOf0(W1,W0)
         => sdtpldt0(sdtmndt0(W0,W1),W1) = W0 ) ) ).

fof(mDiffCons,axiom,
    ! [W0,W1] :
      ( ( aElement0(W0)
        & aSet0(W1) )
     => ( ~ aElementOf0(W0,W1)
       => sdtmndt0(sdtpldt0(W1,W0),W0) = W1 ) ) ).

fof(mCConsSet,axiom,
    ! [W0] :
      ( aElement0(W0)
     => ! [W1] :
          ( ( aSet0(W1)
            & isCountable0(W1) )
         => isCountable0(sdtpldt0(W1,W0)) ) ) ).

fof(mCDiffSet,axiom,
    ! [W0] :
      ( aElement0(W0)
     => ! [W1] :
          ( ( aSet0(W1)
            & isCountable0(W1) )
         => isCountable0(sdtmndt0(W1,W0)) ) ) ).

fof(mFConsSet,axiom,
    ! [W0] :
      ( aElement0(W0)
     => ! [W1] :
          ( ( aSet0(W1)
            & isFinite0(W1) )
         => isFinite0(sdtpldt0(W1,W0)) ) ) ).

fof(mFDiffSet,axiom,
    ! [W0] :
      ( aElement0(W0)
     => ! [W1] :
          ( ( aSet0(W1)
            & isFinite0(W1) )
         => isFinite0(sdtmndt0(W1,W0)) ) ) ).

fof(mNATSet,axiom,
    ( aSet0(szNzAzT0)
    & isCountable0(szNzAzT0) ) ).

fof(mZeroNum,axiom,
    aElementOf0(sz00,szNzAzT0) ).

fof(mSuccNum,axiom,
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => ( aElementOf0(szszuzczcdt0(W0),szNzAzT0)
        & szszuzczcdt0(W0) != sz00 ) ) ).

fof(mSuccEquSucc,axiom,
    ! [W0,W1] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0) )
     => ( szszuzczcdt0(W0) = szszuzczcdt0(W1)
       => W0 = W1 ) ) ).

fof(mNatExtra,axiom,
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => ( W0 = sz00
        | ? [W1] :
            ( aElementOf0(W1,szNzAzT0)
            & W0 = szszuzczcdt0(W1) ) ) ) ).

fof(mNatNSucc,axiom,
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => W0 != szszuzczcdt0(W0) ) ).

fof(mLessRel,axiom,
    ! [W0,W1] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0) )
     => ( sdtlseqdt0(W0,W1)
       => $true ) ) ).

fof(mZeroLess,axiom,
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => sdtlseqdt0(sz00,W0) ) ).

fof(mNoScLessZr,axiom,
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => ~ sdtlseqdt0(szszuzczcdt0(W0),sz00) ) ).

fof(mSuccLess,axiom,
    ! [W0,W1] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0) )
     => ( sdtlseqdt0(W0,W1)
      <=> sdtlseqdt0(szszuzczcdt0(W0),szszuzczcdt0(W1)) ) ) ).

fof(mLessSucc,axiom,
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => sdtlseqdt0(W0,szszuzczcdt0(W0)) ) ).

fof(mLessRefl,axiom,
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => sdtlseqdt0(W0,W0) ) ).

fof(mLessASymm,axiom,
    ! [W0,W1] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0) )
     => ( ( sdtlseqdt0(W0,W1)
          & sdtlseqdt0(W1,W0) )
       => W0 = W1 ) ) ).

fof(mLessTrans,axiom,
    ! [W0,W1,W2] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0)
        & aElementOf0(W2,szNzAzT0) )
     => ( ( sdtlseqdt0(W0,W1)
          & sdtlseqdt0(W1,W2) )
       => sdtlseqdt0(W0,W2) ) ) ).

fof(mLessTotal,axiom,
    ! [W0,W1] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0) )
     => ( sdtlseqdt0(W0,W1)
        | sdtlseqdt0(szszuzczcdt0(W1),W0) ) ) ).

fof(mIHSort,axiom,
    ! [W0,W1] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0) )
     => ( iLess0(W0,W1)
       => $true ) ) ).

fof(mIH,axiom,
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => iLess0(W0,szszuzczcdt0(W0)) ) ).

fof(mCardS,axiom,
    ! [W0] :
      ( aSet0(W0)
     => aElement0(sbrdtbr0(W0)) ) ).

fof(mCardNum,axiom,
    ! [W0] :
      ( aSet0(W0)
     => ( aElementOf0(sbrdtbr0(W0),szNzAzT0)
      <=> isFinite0(W0) ) ) ).

fof(mCardEmpty,axiom,
    ! [W0] :
      ( aSet0(W0)
     => ( sbrdtbr0(W0) = sz00
      <=> W0 = slcrc0 ) ) ).

fof(mCardCons,axiom,
    ! [W0] :
      ( ( aSet0(W0)
        & isFinite0(W0) )
     => ! [W1] :
          ( aElement0(W1)
         => ( ~ aElementOf0(W1,W0)
           => sbrdtbr0(sdtpldt0(W0,W1)) = szszuzczcdt0(sbrdtbr0(W0)) ) ) ) ).

fof(mCardDiff,axiom,
    ! [W0] :
      ( aSet0(W0)
     => ! [W1] :
          ( ( isFinite0(W0)
            & aElementOf0(W1,W0) )
         => szszuzczcdt0(sbrdtbr0(sdtmndt0(W0,W1))) = sbrdtbr0(W0) ) ) ).

fof(mCardSub,axiom,
    ! [W0] :
      ( aSet0(W0)
     => ! [W1] :
          ( ( isFinite0(W0)
            & aSubsetOf0(W1,W0) )
         => sdtlseqdt0(sbrdtbr0(W1),sbrdtbr0(W0)) ) ) ).

fof(mCardSubEx,axiom,
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aElementOf0(W1,szNzAzT0) )
     => ( ( isFinite0(W0)
          & sdtlseqdt0(W1,sbrdtbr0(W0)) )
       => ? [W2] :
            ( aSubsetOf0(W2,W0)
            & sbrdtbr0(W2) = W1 ) ) ) ).

fof(mDefMin,definition,
    ! [W0] :
      ( ( aSubsetOf0(W0,szNzAzT0)
        & W0 != slcrc0 )
     => ! [W1] :
          ( W1 = szmzizndt0(W0)
        <=> ( aElementOf0(W1,W0)
            & ! [W2] :
                ( aElementOf0(W2,W0)
               => sdtlseqdt0(W1,W2) ) ) ) ) ).

fof(mDefMax,definition,
    ! [W0] :
      ( ( aSubsetOf0(W0,szNzAzT0)
        & isFinite0(W0)
        & W0 != slcrc0 )
     => ! [W1] :
          ( W1 = szmzazxdt0(W0)
        <=> ( aElementOf0(W1,W0)
            & ! [W2] :
                ( aElementOf0(W2,W0)
               => sdtlseqdt0(W2,W1) ) ) ) ) ).

fof(mMinMin,axiom,
    ! [W0,W1] :
      ( ( aSubsetOf0(W0,szNzAzT0)
        & aSubsetOf0(W1,szNzAzT0)
        & W0 != slcrc0
        & W1 != slcrc0 )
     => ( ( aElementOf0(szmzizndt0(W0),W1)
          & aElementOf0(szmzizndt0(W1),W0) )
       => szmzizndt0(W0) = szmzizndt0(W1) ) ) ).

fof(mDefSeg,definition,
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => ! [W1] :
          ( W1 = slbdtrb0(W0)
        <=> ( aSet0(W1)
            & ! [W2] :
                ( aElementOf0(W2,W1)
              <=> ( aElementOf0(W2,szNzAzT0)
                  & sdtlseqdt0(szszuzczcdt0(W2),W0) ) ) ) ) ) ).

fof(mSegFin,axiom,
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => isFinite0(slbdtrb0(W0)) ) ).

fof(mSegZero,axiom,
    slbdtrb0(sz00) = slcrc0 ).

fof(mSegSucc,axiom,
    ! [W0,W1] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0) )
     => ( aElementOf0(W0,slbdtrb0(szszuzczcdt0(W1)))
      <=> ( aElementOf0(W0,slbdtrb0(W1))
          | W0 = W1 ) ) ) ).

fof(mSegLess,axiom,
    ! [W0,W1] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0) )
     => ( sdtlseqdt0(W0,W1)
      <=> aSubsetOf0(slbdtrb0(W0),slbdtrb0(W1)) ) ) ).

fof(mFinSubSeg,axiom,
    ! [W0] :
      ( ( aSubsetOf0(W0,szNzAzT0)
        & isFinite0(W0) )
     => ? [W1] :
          ( aElementOf0(W1,szNzAzT0)
          & aSubsetOf0(W0,slbdtrb0(W1)) ) ) ).

fof(mCardSeg,axiom,
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => sbrdtbr0(slbdtrb0(W0)) = W0 ) ).

fof(mDefSel,definition,
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aElementOf0(W1,szNzAzT0) )
     => ! [W2] :
          ( W2 = slbdtsldtrb0(W0,W1)
        <=> ( aSet0(W2)
            & ! [W3] :
                ( aElementOf0(W3,W2)
              <=> ( aSubsetOf0(W3,W0)
                  & sbrdtbr0(W3) = W1 ) ) ) ) ) ).

fof(mSelFSet,axiom,
    ! [W0] :
      ( ( aSet0(W0)
        & isFinite0(W0) )
     => ! [W1] :
          ( aElementOf0(W1,szNzAzT0)
         => isFinite0(slbdtsldtrb0(W0,W1)) ) ) ).

fof(mSelNSet,axiom,
    ! [W0] :
      ( ( aSet0(W0)
        & ~ isFinite0(W0) )
     => ! [W1] :
          ( aElementOf0(W1,szNzAzT0)
         => slbdtsldtrb0(W0,W1) != slcrc0 ) ) ).

fof(mSelCSet,axiom,
    ! [W0] :
      ( ( aSet0(W0)
        & isCountable0(W0) )
     => ! [W1] :
          ( ( aElementOf0(W1,szNzAzT0)
            & W1 != sz00 )
         => isCountable0(slbdtsldtrb0(W0,W1)) ) ) ).

fof(mSelSub,axiom,
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => ! [W1,W2] :
          ( ( aSet0(W1)
            & aSet0(W2)
            & W0 != sz00 )
         => ( ( aSubsetOf0(slbdtsldtrb0(W1,W0),slbdtsldtrb0(W2,W0))
              & slbdtsldtrb0(W1,W0) != slcrc0 )
           => aSubsetOf0(W1,W2) ) ) ) ).

fof(mSelExtra,axiom,
    ! [W0,W1] :
      ( ( aSet0(W0)
        & aElementOf0(W1,szNzAzT0) )
     => ! [W2] :
          ( ( aSubsetOf0(W2,slbdtsldtrb0(W0,W1))
            & isFinite0(W2) )
         => ? [W3] :
              ( aSubsetOf0(W3,W0)
              & isFinite0(W3)
              & aSubsetOf0(W2,slbdtsldtrb0(W3,W1)) ) ) ) ).

fof(mFunSort,axiom,
    ! [W0] :
      ( aFunction0(W0)
     => $true ) ).

fof(mDomSet,axiom,
    ! [W0] :
      ( aFunction0(W0)
     => aSet0(szDzozmdt0(W0)) ) ).

fof(mImgElm,axiom,
    ! [W0] :
      ( aFunction0(W0)
     => ! [W1] :
          ( aElementOf0(W1,szDzozmdt0(W0))
         => aElement0(sdtlpdtrp0(W0,W1)) ) ) ).

fof(mDefPtt,definition,
    ! [W0,W1] :
      ( ( aFunction0(W0)
        & aElement0(W1) )
     => ! [W2] :
          ( W2 = sdtlbdtrb0(W0,W1)
        <=> ( aSet0(W2)
            & ! [W3] :
                ( aElementOf0(W3,W2)
              <=> ( aElementOf0(W3,szDzozmdt0(W0))
                  & sdtlpdtrp0(W0,W3) = W1 ) ) ) ) ) ).

fof(mPttSet,axiom,
    ! [W0,W1] :
      ( ( aFunction0(W0)
        & aElement0(W1) )
     => aSubsetOf0(sdtlbdtrb0(W0,W1),szDzozmdt0(W0)) ) ).

fof(mDefSImg,definition,
    ! [W0] :
      ( aFunction0(W0)
     => ! [W1] :
          ( aSubsetOf0(W1,szDzozmdt0(W0))
         => ! [W2] :
              ( W2 = sdtlcdtrc0(W0,W1)
            <=> ( aSet0(W2)
                & ! [W3] :
                    ( aElementOf0(W3,W2)
                  <=> ? [W4] :
                        ( aElementOf0(W4,W1)
                        & sdtlpdtrp0(W0,W4) = W3 ) ) ) ) ) ) ).

fof(mImgRng,axiom,
    ! [W0] :
      ( aFunction0(W0)
     => ! [W1] :
          ( aElementOf0(W1,szDzozmdt0(W0))
         => aElementOf0(sdtlpdtrp0(W0,W1),sdtlcdtrc0(W0,szDzozmdt0(W0))) ) ) ).

fof(mDefRst,definition,
    ! [W0] :
      ( aFunction0(W0)
     => ! [W1] :
          ( aSubsetOf0(W1,szDzozmdt0(W0))
         => ! [W2] :
              ( W2 = sdtexdt0(W0,W1)
            <=> ( aFunction0(W2)
                & szDzozmdt0(W2) = W1
                & ! [W3] :
                    ( aElementOf0(W3,W1)
                   => sdtlpdtrp0(W2,W3) = sdtlpdtrp0(W0,W3) ) ) ) ) ) ).

fof(mImgCount,axiom,
    ! [W0] :
      ( aFunction0(W0)
     => ! [W1] :
          ( ( aSubsetOf0(W1,szDzozmdt0(W0))
            & isCountable0(W1) )
         => ( ! [W2,W3] :
                ( ( aElementOf0(W2,szDzozmdt0(W0))
                  & aElementOf0(W3,szDzozmdt0(W0))
                  & W2 != W3 )
               => sdtlpdtrp0(W0,W2) != sdtlpdtrp0(W0,W3) )
           => isCountable0(sdtlcdtrc0(W0,W1)) ) ) ) ).

fof(mDirichlet,axiom,
    ! [W0] :
      ( aFunction0(W0)
     => ( ( isCountable0(szDzozmdt0(W0))
          & isFinite0(sdtlcdtrc0(W0,szDzozmdt0(W0))) )
       => ( aElement0(szDzizrdt0(W0))
          & isCountable0(sdtlbdtrb0(W0,szDzizrdt0(W0))) ) ) ) ).

fof(m__3291,hypothesis,
    ( aSet0(xT)
    & isFinite0(xT) ) ).

fof(m__3418,hypothesis,
    aElementOf0(xK,szNzAzT0) ).

fof(m__3435,hypothesis,
    ( aSet0(xS)
    & ! [W0] :
        ( aElementOf0(W0,xS)
       => aElementOf0(W0,szNzAzT0) )
    & aSubsetOf0(xS,szNzAzT0)
    & isCountable0(xS) ) ).

fof(m__3453,hypothesis,
    ( aFunction0(xc)
    & ! [W0] :
        ( ( aElementOf0(W0,szDzozmdt0(xc))
         => ( aSet0(W0)
            & ! [W1] :
                ( aElementOf0(W1,W0)
               => aElementOf0(W1,xS) )
            & aSubsetOf0(W0,xS)
            & sbrdtbr0(W0) = xK ) )
        & ( ( ( ( aSet0(W0)
                & ! [W1] :
                    ( aElementOf0(W1,W0)
                   => aElementOf0(W1,xS) ) )
              | aSubsetOf0(W0,xS) )
            & sbrdtbr0(W0) = xK )
         => aElementOf0(W0,szDzozmdt0(xc)) ) )
    & szDzozmdt0(xc) = slbdtsldtrb0(xS,xK)
    & aSet0(sdtlcdtrc0(xc,szDzozmdt0(xc)))
    & ! [W0] :
        ( aElementOf0(W0,sdtlcdtrc0(xc,szDzozmdt0(xc)))
      <=> ? [W1] :
            ( aElementOf0(W1,szDzozmdt0(xc))
            & sdtlpdtrp0(xc,W1) = W0 ) )
    & ! [W0] :
        ( aElementOf0(W0,sdtlcdtrc0(xc,szDzozmdt0(xc)))
       => aElementOf0(W0,xT) )
    & aSubsetOf0(sdtlcdtrc0(xc,szDzozmdt0(xc)),xT) ) ).

fof(m__3398,hypothesis,
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => ! [W1] :
          ( ( ( ( aSet0(W1)
                & ! [W2] :
                    ( aElementOf0(W2,W1)
                   => aElementOf0(W2,szNzAzT0) ) )
              | aSubsetOf0(W1,szNzAzT0) )
            & isCountable0(W1) )
         => ! [W2] :
              ( ( aFunction0(W2)
                & ( ! [W3] :
                      ( ( aElementOf0(W3,szDzozmdt0(W2))
                       => ( ( ( aSet0(W3)
                              & ! [W4] :
                                  ( aElementOf0(W4,W3)
                                 => aElementOf0(W4,W1) ) )
                            | aSubsetOf0(W3,W1) )
                          & sbrdtbr0(W3) = W0 ) )
                      & ( ( aSet0(W3)
                          & ! [W4] :
                              ( aElementOf0(W4,W3)
                             => aElementOf0(W4,W1) )
                          & aSubsetOf0(W3,W1)
                          & sbrdtbr0(W3) = W0 )
                       => aElementOf0(W3,szDzozmdt0(W2)) ) )
                  | szDzozmdt0(W2) = slbdtsldtrb0(W1,W0) )
                & ( ( aSet0(sdtlcdtrc0(W2,szDzozmdt0(W2)))
                    & ! [W3] :
                        ( aElementOf0(W3,sdtlcdtrc0(W2,szDzozmdt0(W2)))
                      <=> ? [W4] :
                            ( aElementOf0(W4,szDzozmdt0(W2))
                            & sdtlpdtrp0(W2,W4) = W3 ) ) )
                 => ( ! [W3] :
                        ( aElementOf0(W3,sdtlcdtrc0(W2,szDzozmdt0(W2)))
                       => aElementOf0(W3,xT) )
                    | aSubsetOf0(sdtlcdtrc0(W2,szDzozmdt0(W2)),xT) ) ) )
             => ( iLess0(W0,xK)
               => ? [W3] :
                    ( aElementOf0(W3,xT)
                    & ? [W4] :
                        ( aSet0(W4)
                        & ! [W5] :
                            ( aElementOf0(W5,W4)
                           => aElementOf0(W5,W1) )
                        & aSubsetOf0(W4,W1)
                        & isCountable0(W4)
                        & ! [W5] :
                            ( ( ( ( ( aSet0(W5)
                                    & ! [W6] :
                                        ( aElementOf0(W6,W5)
                                       => aElementOf0(W6,W4) ) )
                                  | aSubsetOf0(W5,W4) )
                                & sbrdtbr0(W5) = W0 )
                              | aElementOf0(W5,slbdtsldtrb0(W4,W0)) )
                           => sdtlpdtrp0(W2,W5) = W3 ) ) ) ) ) ) ) ).

fof(m__3462,hypothesis,
    xK != sz00 ).

fof(m__3520,hypothesis,
    xK != sz00 ).

fof(m__3533,hypothesis,
    ( aElementOf0(xk,szNzAzT0)
    & szszuzczcdt0(xk) = xK ) ).

fof(m__3623,hypothesis,
    ( aFunction0(xN)
    & szDzozmdt0(xN) = szNzAzT0
    & sdtlpdtrp0(xN,sz00) = xS
    & ! [W0] :
        ( aElementOf0(W0,szNzAzT0)
       => ( ( ( ( aSet0(sdtlpdtrp0(xN,W0))
                & ! [W1] :
                    ( aElementOf0(W1,sdtlpdtrp0(xN,W0))
                   => aElementOf0(W1,szNzAzT0) ) )
              | aSubsetOf0(sdtlpdtrp0(xN,W0),szNzAzT0) )
            & isCountable0(sdtlpdtrp0(xN,W0)) )
         => ( aElementOf0(szmzizndt0(sdtlpdtrp0(xN,W0)),sdtlpdtrp0(xN,W0))
            & ! [W1] :
                ( aElementOf0(W1,sdtlpdtrp0(xN,W0))
               => sdtlseqdt0(szmzizndt0(sdtlpdtrp0(xN,W0)),W1) )
            & aSet0(sdtmndt0(sdtlpdtrp0(xN,W0),szmzizndt0(sdtlpdtrp0(xN,W0))))
            & ! [W1] :
                ( aElementOf0(W1,sdtmndt0(sdtlpdtrp0(xN,W0),szmzizndt0(sdtlpdtrp0(xN,W0))))
              <=> ( aElement0(W1)
                  & aElementOf0(W1,sdtlpdtrp0(xN,W0))
                  & W1 != szmzizndt0(sdtlpdtrp0(xN,W0)) ) )
            & aSet0(sdtlpdtrp0(xN,szszuzczcdt0(W0)))
            & ! [W1] :
                ( aElementOf0(W1,sdtlpdtrp0(xN,szszuzczcdt0(W0)))
               => aElementOf0(W1,sdtmndt0(sdtlpdtrp0(xN,W0),szmzizndt0(sdtlpdtrp0(xN,W0)))) )
            & aSubsetOf0(sdtlpdtrp0(xN,szszuzczcdt0(W0)),sdtmndt0(sdtlpdtrp0(xN,W0),szmzizndt0(sdtlpdtrp0(xN,W0))))
            & isCountable0(sdtlpdtrp0(xN,szszuzczcdt0(W0))) ) ) ) ) ).

fof(m__3671,hypothesis,
    ! [W0] :
      ( aElementOf0(W0,szNzAzT0)
     => ( aSet0(sdtlpdtrp0(xN,W0))
        & ! [W1] :
            ( aElementOf0(W1,sdtlpdtrp0(xN,W0))
           => aElementOf0(W1,szNzAzT0) )
        & aSubsetOf0(sdtlpdtrp0(xN,W0),szNzAzT0)
        & isCountable0(sdtlpdtrp0(xN,W0)) ) ) ).

fof(m__3786,hypothesis,
    ( aElementOf0(xj,szNzAzT0)
    & aElementOf0(xi,szNzAzT0) ) ).

fof(m__3754,hypothesis,
    ! [W0,W1] :
      ( ( aElementOf0(W0,szNzAzT0)
        & aElementOf0(W1,szNzAzT0) )
     => ( sdtlseqdt0(W1,W0)
       => ( iLess0(W0,xi)
         => ( ! [W2] :
                ( aElementOf0(W2,sdtlpdtrp0(xN,W0))
               => aElementOf0(W2,sdtlpdtrp0(xN,W1)) )
            & aSubsetOf0(sdtlpdtrp0(xN,W0),sdtlpdtrp0(xN,W1)) ) ) ) ) ).

fof(m__3786_02,hypothesis,
    ( ( sdtlseqdt0(xj,xi)
      & ? [W0] :
          ( aElementOf0(W0,szNzAzT0)
          & szszuzczcdt0(W0) = xi ) )
   => ( sdtlseqdt0(xj,xi)
     => ( ! [W0] :
            ( aElementOf0(W0,sdtlpdtrp0(xN,xi))
           => aElementOf0(W0,sdtlpdtrp0(xN,xj)) )
        & aSubsetOf0(sdtlpdtrp0(xN,xi),sdtlpdtrp0(xN,xj)) ) ) ) ).

fof(m__,conjecture,
    ( sdtlseqdt0(xj,xi)
   => ( ! [W0] :
          ( aElementOf0(W0,sdtlpdtrp0(xN,xi))
         => aElementOf0(W0,sdtlpdtrp0(xN,xj)) )
      | aSubsetOf0(sdtlpdtrp0(xN,xi),sdtlpdtrp0(xN,xj)) ) ) ).

%------------------------------------------------------------------------------
