%------------------------------------------------------------------------------
% File     : NUM925+5 : TPTP v8.1.0. Released v5.3.0.
% Domain   : Number Theory
% Problem  : Sum of two squares line 192, 100 axioms selected
% Version  : Especial.
% English  :

% Refs     : [BN10]  Boehme & Nipkow (2010), Sledgehammer: Judgement Day
%          : [Bla11] Blanchette (2011), Email to Geoff Sutcliffe
% Source   : [Bla11]
% Names    : s2s_100_fofpt_l192 [Bla11]

% Status   : Theorem
% Rating   : 0.25 v8.1.0, 0.22 v7.5.0, 0.25 v7.4.0, 0.13 v7.3.0, 0.21 v7.2.0, 0.24 v7.1.0, 0.22 v7.0.0, 0.20 v6.4.0, 0.27 v6.3.0, 0.21 v6.2.0, 0.28 v6.1.0, 0.43 v6.0.0, 0.26 v5.5.0, 0.44 v5.4.0, 0.50 v5.3.0
% Syntax   : Number of formulae    :  153 (  73 unt;   0 def)
%            Number of atoms       :  289 ( 120 equ)
%            Maximal formula atoms :    7 (   1 avg)
%            Number of connectives :  154 (  18   ~;   4   |;  32   &)
%                                         (  38 <=>;  62  =>;   0  <=;   0 <~>)
%            Maximal formula depth :    8 (   3 avg)
%            Maximal term depth    :    6 (   1 avg)
%            Number of predicates  :   15 (  14 usr;   0 prp; 1-3 aty)
%            Number of functors    :   15 (  15 usr;   5 con; 0-3 aty)
%            Number of variables   :  210 ( 210   !;   0   ?)
% SPC      : FOF_THM_RFO_SEQ

% Comments : This file was generated by Isabelle (most likely Sledgehammer)
%            2011-08-09 14:09:06
%          : Encoded with polymorphic tags.
%------------------------------------------------------------------------------
%----Explicit typings (32)
fof(tsy_c_Groups_Oone__class_Oone_res,axiom,
    ! [X_a] :
      ( ( power(X_a)
        & semiring_0(X_a) )
     => ti(X_a,one_one(X_a)) = one_one(X_a) ) ).

fof(tsy_c_Groups_Oplus__class_Oplus_0_arg1,axiom,
    ! [B_1,B_2,X_a] :
      ( linord219039673up_add(X_a)
     => plus_plus(X_a,ti(X_a,B_1),B_2) = plus_plus(X_a,B_1,B_2) ) ).

fof(tsy_c_Groups_Oplus__class_Oplus_0_arg2,axiom,
    ! [B_1,B_2,X_a] :
      ( linord219039673up_add(X_a)
     => plus_plus(X_a,B_1,ti(X_a,B_2)) = plus_plus(X_a,B_1,B_2) ) ).

fof(tsy_c_Groups_Oplus__class_Oplus_0_res,axiom,
    ! [B_1,B_2,X_a] :
      ( linord219039673up_add(X_a)
     => ti(X_a,plus_plus(X_a,B_1,B_2)) = plus_plus(X_a,B_1,B_2) ) ).

fof(tsy_c_Groups_Oplus__class_Oplus_1_arg1,axiom,
    ! [B_1,B_2,X_a] :
      ( number_semiring(X_a)
     => plus_plus(X_a,ti(X_a,B_1),B_2) = plus_plus(X_a,B_1,B_2) ) ).

fof(tsy_c_Groups_Oplus__class_Oplus_1_arg2,axiom,
    ! [B_1,B_2,X_a] :
      ( number_semiring(X_a)
     => plus_plus(X_a,B_1,ti(X_a,B_2)) = plus_plus(X_a,B_1,B_2) ) ).

fof(tsy_c_Groups_Oplus__class_Oplus_1_res,axiom,
    ! [B_1,B_2,X_a] :
      ( number_semiring(X_a)
     => ti(X_a,plus_plus(X_a,B_1,B_2)) = plus_plus(X_a,B_1,B_2) ) ).

fof(tsy_c_Groups_Ozero__class_Ozero_0_res,axiom,
    ! [X_a] :
      ( ( power(X_a)
        & mult_zero(X_a)
        & no_zero_divisors(X_a)
        & zero_neq_one(X_a) )
     => ti(X_a,zero_zero(X_a)) = zero_zero(X_a) ) ).

fof(tsy_c_Groups_Ozero__class_Ozero_1_res,axiom,
    ! [X_a] :
      ( linord219039673up_add(X_a)
     => ti(X_a,zero_zero(X_a)) = zero_zero(X_a) ) ).

fof(tsy_c_Groups_Ozero__class_Ozero_2_res,axiom,
    ! [X_a] :
      ( ( power(X_a)
        & semiring_0(X_a) )
     => ti(X_a,zero_zero(X_a)) = zero_zero(X_a) ) ).

fof(tsy_c_HOL_Oundefined_res,axiom,
    ! [X_a] : ti(X_a,undefined(X_a)) = undefined(X_a) ).

fof(tsy_c_Int_OBit0_arg1,hypothesis,
    ! [B_1] : bit0(ti(int,B_1)) = bit0(B_1) ).

fof(tsy_c_Int_OBit0_res,hypothesis,
    ! [B_1] : ti(int,bit0(B_1)) = bit0(B_1) ).

fof(tsy_c_Int_OBit1_arg1,hypothesis,
    ! [B_1] : bit1(ti(int,B_1)) = bit1(B_1) ).

fof(tsy_c_Int_OBit1_res,hypothesis,
    ! [B_1] : ti(int,bit1(B_1)) = bit1(B_1) ).

fof(tsy_c_Int_OPls_res,hypothesis,
    ti(int,pls) = pls ).

fof(tsy_c_Int_Onumber__class_Onumber__of_arg1,axiom,
    ! [B_1,X_a] :
      ( number(X_a)
     => number_number_of(X_a,ti(int,B_1)) = number_number_of(X_a,B_1) ) ).

fof(tsy_c_Int_Onumber__class_Onumber__of_res,axiom,
    ! [B_1,X_a] :
      ( number(X_a)
     => ti(X_a,number_number_of(X_a,B_1)) = number_number_of(X_a,B_1) ) ).

fof(tsy_c_Nat_Osemiring__1__class_Oof__nat_arg1,axiom,
    ! [B_1,X_a] :
      ( number_semiring(X_a)
     => semiring_1_of_nat(X_a,ti(nat,B_1)) = semiring_1_of_nat(X_a,B_1) ) ).

fof(tsy_c_Nat_Osemiring__1__class_Oof__nat_res,axiom,
    ! [B_1,X_a] :
      ( number_semiring(X_a)
     => ti(X_a,semiring_1_of_nat(X_a,B_1)) = semiring_1_of_nat(X_a,B_1) ) ).

fof(tsy_c_Orderings_Oord__class_Oless_0_arg1,axiom,
    ! [B_1,B_2,X_a] :
      ( linordered_idom(X_a)
     => ( ord_less(X_a,ti(X_a,B_1),B_2)
      <=> ord_less(X_a,B_1,B_2) ) ) ).

fof(tsy_c_Orderings_Oord__class_Oless_0_arg2,axiom,
    ! [B_1,B_2,X_a] :
      ( linordered_idom(X_a)
     => ( ord_less(X_a,B_1,ti(X_a,B_2))
      <=> ord_less(X_a,B_1,B_2) ) ) ).

fof(tsy_c_Orderings_Oord__class_Oless_1_arg1,axiom,
    ! [B_1,B_2] :
      ( ord_less(nat,ti(nat,B_1),B_2)
    <=> ord_less(nat,B_1,B_2) ) ).

fof(tsy_c_Orderings_Oord__class_Oless_1_arg2,axiom,
    ! [B_1,B_2] :
      ( ord_less(nat,B_1,ti(nat,B_2))
    <=> ord_less(nat,B_1,B_2) ) ).

fof(tsy_c_Power_Opower__class_Opower_0_arg1,axiom,
    ! [B_1,B_2,X_a] :
      ( ( power(X_a)
        & mult_zero(X_a)
        & no_zero_divisors(X_a)
        & zero_neq_one(X_a) )
     => power_power(X_a,ti(X_a,B_1),B_2) = power_power(X_a,B_1,B_2) ) ).

fof(tsy_c_Power_Opower__class_Opower_0_arg2,axiom,
    ! [B_1,B_2,X_a] :
      ( ( power(X_a)
        & mult_zero(X_a)
        & no_zero_divisors(X_a)
        & zero_neq_one(X_a) )
     => power_power(X_a,B_1,ti(nat,B_2)) = power_power(X_a,B_1,B_2) ) ).

fof(tsy_c_Power_Opower__class_Opower_0_res,axiom,
    ! [B_1,B_2,X_a] :
      ( ( power(X_a)
        & mult_zero(X_a)
        & no_zero_divisors(X_a)
        & zero_neq_one(X_a) )
     => ti(X_a,power_power(X_a,B_1,B_2)) = power_power(X_a,B_1,B_2) ) ).

fof(tsy_c_Power_Opower__class_Opower_1_arg1,axiom,
    ! [B_1,B_2,X_a] :
      ( ( power(X_a)
        & semiring_0(X_a) )
     => power_power(X_a,ti(X_a,B_1),B_2) = power_power(X_a,B_1,B_2) ) ).

fof(tsy_c_Power_Opower__class_Opower_1_arg2,axiom,
    ! [B_1,B_2,X_a] :
      ( ( power(X_a)
        & semiring_0(X_a) )
     => power_power(X_a,B_1,ti(nat,B_2)) = power_power(X_a,B_1,B_2) ) ).

fof(tsy_c_Power_Opower__class_Opower_1_res,axiom,
    ! [B_1,B_2,X_a] :
      ( ( power(X_a)
        & semiring_0(X_a) )
     => ti(X_a,power_power(X_a,B_1,B_2)) = power_power(X_a,B_1,B_2) ) ).

fof(tsy_v_n_____res,hypothesis,
    ti(nat,n) = n ).

fof(tsy_v_t_____res,axiom,
    ti(int,t) = t ).

%----Relevant facts (98)
fof(fact_0_n1pos,axiom,
    ord_less(int,zero_zero(int),plus_plus(int,one_one(int),semiring_1_of_nat(int,n))) ).

fof(fact_1_t1,axiom,
    ord_less(int,one_one(int),t) ).

fof(fact_2_sum__power2__eq__zero__iff,axiom,
    ! [X_a] :
      ( linordered_idom(X_a)
     => ! [Xa,Ya] :
          ( plus_plus(X_a,power_power(X_a,Xa,number_number_of(nat,bit0(bit1(pls)))),power_power(X_a,Ya,number_number_of(nat,bit0(bit1(pls))))) = zero_zero(X_a)
        <=> ( ti(X_a,Xa) = zero_zero(X_a)
            & ti(X_a,Ya) = zero_zero(X_a) ) ) ) ).

fof(fact_3_one__power2,axiom,
    ! [X_a] :
      ( semiring_1(X_a)
     => power_power(X_a,one_one(X_a),number_number_of(nat,bit0(bit1(pls)))) = one_one(X_a) ) ).

fof(fact_4_zero__power2,axiom,
    ! [X_a] :
      ( semiring_1(X_a)
     => power_power(X_a,zero_zero(X_a),number_number_of(nat,bit0(bit1(pls)))) = zero_zero(X_a) ) ).

fof(fact_5_zero__eq__power2,axiom,
    ! [X_a] :
      ( ring_11004092258visors(X_a)
     => ! [A_2] :
          ( power_power(X_a,A_2,number_number_of(nat,bit0(bit1(pls)))) = zero_zero(X_a)
        <=> ti(X_a,A_2) = zero_zero(X_a) ) ) ).

fof(fact_6_add__special_I2_J,axiom,
    ! [X_a] :
      ( number_ring(X_a)
     => ! [W] : plus_plus(X_a,one_one(X_a),number_number_of(X_a,W)) = number_number_of(X_a,plus_plus(int,bit1(pls),W)) ) ).

fof(fact_7_add__special_I3_J,axiom,
    ! [X_a] :
      ( number_ring(X_a)
     => ! [V] : plus_plus(X_a,number_number_of(X_a,V),one_one(X_a)) = number_number_of(X_a,plus_plus(int,V,bit1(pls))) ) ).

fof(fact_8_one__add__one__is__two,axiom,
    ! [X_a] :
      ( number_ring(X_a)
     => plus_plus(X_a,one_one(X_a),one_one(X_a)) = number_number_of(X_a,bit0(bit1(pls))) ) ).

fof(fact_9_semiring__one__add__one__is__two,axiom,
    ! [X_a] :
      ( number_semiring(X_a)
     => plus_plus(X_a,one_one(X_a),one_one(X_a)) = number_number_of(X_a,bit0(bit1(pls))) ) ).

fof(fact_10_quartic__square__square,axiom,
    ! [X] : power_power(int,power_power(int,X,number_number_of(nat,bit0(bit1(pls)))),number_number_of(nat,bit0(bit1(pls)))) = power_power(int,X,number_number_of(nat,bit0(bit0(bit1(pls))))) ).

fof(fact_11_power__0__left__number__of,axiom,
    ! [X_a] :
      ( ( power(X_a)
        & semiring_0(X_a) )
     => ! [W] :
          ( ( number_number_of(nat,W) = zero_zero(nat)
           => power_power(X_a,zero_zero(X_a),number_number_of(nat,W)) = one_one(X_a) )
          & ( number_number_of(nat,W) != zero_zero(nat)
           => power_power(X_a,zero_zero(X_a),number_number_of(nat,W)) = zero_zero(X_a) ) ) ) ).

fof(fact_12_semiring__norm_I110_J,axiom,
    ! [X_a] :
      ( number_ring(X_a)
     => one_one(X_a) = number_number_of(X_a,bit1(pls)) ) ).

fof(fact_13_numeral__1__eq__1,axiom,
    ! [X_a] :
      ( number_ring(X_a)
     => number_number_of(X_a,bit1(pls)) = one_one(X_a) ) ).

fof(fact_14_n0,axiom,
    ord_less(nat,zero_zero(nat),n) ).

fof(fact_15_zless__linear,axiom,
    ! [X,Y] :
      ( ord_less(int,X,Y)
      | X = Y
      | ord_less(int,Y,X) ) ).

fof(fact_16_less__number__of__int__code,axiom,
    ! [K_1,L_1] :
      ( ord_less(int,number_number_of(int,K_1),number_number_of(int,L_1))
    <=> ord_less(int,K_1,L_1) ) ).

fof(fact_17_plus__numeral__code_I9_J,axiom,
    ! [V,W] : plus_plus(int,number_number_of(int,V),number_number_of(int,W)) = number_number_of(int,plus_plus(int,V,W)) ).

fof(fact_18_less__number__of,axiom,
    ! [X_a] :
      ( ( number_ring(X_a)
        & linordered_idom(X_a) )
     => ! [Xa,Ya] :
          ( ord_less(X_a,number_number_of(X_a,Xa),number_number_of(X_a,Ya))
        <=> ord_less(int,Xa,Ya) ) ) ).

fof(fact_19_zero__is__num__zero,axiom,
    zero_zero(int) = number_number_of(int,pls) ).

fof(fact_20_zpower__int,axiom,
    ! [M,N] : power_power(int,semiring_1_of_nat(int,M),N) = semiring_1_of_nat(int,power_power(nat,M,N)) ).

fof(fact_21_int__power,axiom,
    ! [M,N] : semiring_1_of_nat(int,power_power(nat,M,N)) = power_power(int,semiring_1_of_nat(int,M),N) ).

fof(fact_22_zadd__int__left,axiom,
    ! [M,N,Z] : plus_plus(int,semiring_1_of_nat(int,M),plus_plus(int,semiring_1_of_nat(int,N),Z)) = plus_plus(int,semiring_1_of_nat(int,plus_plus(nat,M,N)),Z) ).

fof(fact_23_zadd__int,axiom,
    ! [M,N] : plus_plus(int,semiring_1_of_nat(int,M),semiring_1_of_nat(int,N)) = semiring_1_of_nat(int,plus_plus(nat,M,N)) ).

fof(fact_24_int__1,axiom,
    semiring_1_of_nat(int,one_one(nat)) = one_one(int) ).

fof(fact_25_nat__number__of__Pls,axiom,
    number_number_of(nat,pls) = zero_zero(nat) ).

fof(fact_26_semiring__norm_I113_J,axiom,
    zero_zero(nat) = number_number_of(nat,pls) ).

fof(fact_27_int__eq__0__conv,axiom,
    ! [Na] :
      ( semiring_1_of_nat(int,Na) = zero_zero(int)
    <=> Na = zero_zero(nat) ) ).

fof(fact_28_int__0,axiom,
    semiring_1_of_nat(int,zero_zero(nat)) = zero_zero(int) ).

fof(fact_29_nat__1__add__1,axiom,
    plus_plus(nat,one_one(nat),one_one(nat)) = number_number_of(nat,bit0(bit1(pls))) ).

fof(fact_30_less__int__code_I16_J,axiom,
    ! [K1,K2] :
      ( ord_less(int,bit1(K1),bit1(K2))
    <=> ord_less(int,K1,K2) ) ).

fof(fact_31_rel__simps_I17_J,axiom,
    ! [K_1,L_1] :
      ( ord_less(int,bit1(K_1),bit1(L_1))
    <=> ord_less(int,K_1,L_1) ) ).

fof(fact_32_rel__simps_I2_J,axiom,
    ~ ord_less(int,pls,pls) ).

fof(fact_33_less__int__code_I13_J,axiom,
    ! [K1,K2] :
      ( ord_less(int,bit0(K1),bit0(K2))
    <=> ord_less(int,K1,K2) ) ).

fof(fact_34_rel__simps_I14_J,axiom,
    ! [K_1,L_1] :
      ( ord_less(int,bit0(K_1),bit0(L_1))
    <=> ord_less(int,K_1,L_1) ) ).

fof(fact_35_zadd__strict__right__mono,axiom,
    ! [K,I,J] :
      ( ord_less(int,I,J)
     => ord_less(int,plus_plus(int,I,K),plus_plus(int,J,K)) ) ).

fof(fact_36_add__nat__number__of,axiom,
    ! [V_1,V] :
      ( ( ord_less(int,V,pls)
       => plus_plus(nat,number_number_of(nat,V),number_number_of(nat,V_1)) = number_number_of(nat,V_1) )
      & ( ~ ord_less(int,V,pls)
       => ( ( ord_less(int,V_1,pls)
           => plus_plus(nat,number_number_of(nat,V),number_number_of(nat,V_1)) = number_number_of(nat,V) )
          & ( ~ ord_less(int,V_1,pls)
           => plus_plus(nat,number_number_of(nat,V),number_number_of(nat,V_1)) = number_number_of(nat,plus_plus(int,V,V_1)) ) ) ) ) ).

fof(fact_37_one__is__num__one,axiom,
    one_one(int) = number_number_of(int,bit1(pls)) ).

fof(fact_38_nat__numeral__1__eq__1,axiom,
    number_number_of(nat,bit1(pls)) = one_one(nat) ).

fof(fact_39_Numeral1__eq1__nat,axiom,
    one_one(nat) = number_number_of(nat,bit1(pls)) ).

fof(fact_40_eq__number__of,axiom,
    ! [X_a] :
      ( ( number_ring(X_a)
        & ring_char_0(X_a) )
     => ! [Xa,Ya] :
          ( number_number_of(X_a,Xa) = number_number_of(X_a,Ya)
        <=> Xa = Ya ) ) ).

fof(fact_41_number__of__reorient,axiom,
    ! [X_a] :
      ( number(X_a)
     => ! [Wa,Xa] :
          ( number_number_of(X_a,Wa) = ti(X_a,Xa)
        <=> ti(X_a,Xa) = number_number_of(X_a,Wa) ) ) ).

fof(fact_42_rel__simps_I51_J,axiom,
    ! [K_1,L_1] :
      ( bit1(K_1) = bit1(L_1)
    <=> K_1 = L_1 ) ).

fof(fact_43_rel__simps_I48_J,axiom,
    ! [K_1,L_1] :
      ( bit0(K_1) = bit0(L_1)
    <=> K_1 = L_1 ) ).

fof(fact_44_even__less__0__iff,axiom,
    ! [X_a] :
      ( linordered_idom(X_a)
     => ! [A_2] :
          ( ord_less(X_a,plus_plus(X_a,A_2,A_2),zero_zero(X_a))
        <=> ord_less(X_a,A_2,zero_zero(X_a)) ) ) ).

fof(fact_45_zadd__assoc,axiom,
    ! [Z1,Z2,Z3] : plus_plus(int,plus_plus(int,Z1,Z2),Z3) = plus_plus(int,Z1,plus_plus(int,Z2,Z3)) ).

fof(fact_46_zadd__left__commute,axiom,
    ! [X,Y,Z] : plus_plus(int,X,plus_plus(int,Y,Z)) = plus_plus(int,Y,plus_plus(int,X,Z)) ).

fof(fact_47_zadd__commute,axiom,
    ! [Z,W] : plus_plus(int,Z,W) = plus_plus(int,W,Z) ).

fof(fact_48_int__int__eq,axiom,
    ! [Ma,Na] :
      ( semiring_1_of_nat(int,Ma) = semiring_1_of_nat(int,Na)
    <=> Ma = Na ) ).

fof(fact_49_less__special_I3_J,axiom,
    ! [X_a] :
      ( ( number_ring(X_a)
        & linordered_idom(X_a) )
     => ! [Xa] :
          ( ord_less(X_a,number_number_of(X_a,Xa),zero_zero(X_a))
        <=> ord_less(int,Xa,pls) ) ) ).

fof(fact_50_less__special_I1_J,axiom,
    ! [X_a] :
      ( ( number_ring(X_a)
        & linordered_idom(X_a) )
     => ! [Ya] :
          ( ord_less(X_a,zero_zero(X_a),number_number_of(X_a,Ya))
        <=> ord_less(int,pls,Ya) ) ) ).

fof(fact_51_rel__simps_I12_J,axiom,
    ! [K_1] :
      ( ord_less(int,bit1(K_1),pls)
    <=> ord_less(int,K_1,pls) ) ).

fof(fact_52_less__int__code_I15_J,axiom,
    ! [K1,K2] :
      ( ord_less(int,bit1(K1),bit0(K2))
    <=> ord_less(int,K1,K2) ) ).

fof(fact_53_rel__simps_I16_J,axiom,
    ! [K_1,L_1] :
      ( ord_less(int,bit1(K_1),bit0(L_1))
    <=> ord_less(int,K_1,L_1) ) ).

fof(fact_54_rel__simps_I10_J,axiom,
    ! [K_1] :
      ( ord_less(int,bit0(K_1),pls)
    <=> ord_less(int,K_1,pls) ) ).

fof(fact_55_rel__simps_I4_J,axiom,
    ! [K_1] :
      ( ord_less(int,pls,bit0(K_1))
    <=> ord_less(int,pls,K_1) ) ).

fof(fact_56_bin__less__0__simps_I4_J,axiom,
    ! [Wa] :
      ( ord_less(int,bit1(Wa),zero_zero(int))
    <=> ord_less(int,Wa,zero_zero(int)) ) ).

fof(fact_57_bin__less__0__simps_I1_J,axiom,
    ~ ord_less(int,pls,zero_zero(int)) ).

fof(fact_58_bin__less__0__simps_I3_J,axiom,
    ! [Wa] :
      ( ord_less(int,bit0(Wa),zero_zero(int))
    <=> ord_less(int,Wa,zero_zero(int)) ) ).

fof(fact_59_int__0__less__1,axiom,
    ord_less(int,zero_zero(int),one_one(int)) ).

fof(fact_60_zless__add1__eq,axiom,
    ! [Wa,Z_1] :
      ( ord_less(int,Wa,plus_plus(int,Z_1,one_one(int)))
    <=> ( ord_less(int,Wa,Z_1)
        | Wa = Z_1 ) ) ).

fof(fact_61_int__less__0__conv,axiom,
    ! [K] : ~ ord_less(int,semiring_1_of_nat(int,K),zero_zero(int)) ).

fof(fact_62_less__special_I4_J,axiom,
    ! [X_a] :
      ( ( number_ring(X_a)
        & linordered_idom(X_a) )
     => ! [Xa] :
          ( ord_less(X_a,number_number_of(X_a,Xa),one_one(X_a))
        <=> ord_less(int,Xa,bit1(pls)) ) ) ).

fof(fact_63_less__special_I2_J,axiom,
    ! [X_a] :
      ( ( number_ring(X_a)
        & linordered_idom(X_a) )
     => ! [Ya] :
          ( ord_less(X_a,one_one(X_a),number_number_of(X_a,Ya))
        <=> ord_less(int,bit1(pls),Ya) ) ) ).

fof(fact_64_odd__less__0,axiom,
    ! [Z_1] :
      ( ord_less(int,plus_plus(int,plus_plus(int,one_one(int),Z_1),Z_1),zero_zero(int))
    <=> ord_less(int,Z_1,zero_zero(int)) ) ).

fof(fact_65_double__eq__0__iff,axiom,
    ! [X_a] :
      ( linord219039673up_add(X_a)
     => ! [A_2] :
          ( plus_plus(X_a,A_2,A_2) = zero_zero(X_a)
        <=> ti(X_a,A_2) = zero_zero(X_a) ) ) ).

fof(fact_66_rel__simps_I46_J,axiom,
    ! [K] : bit1(K) != pls ).

fof(fact_67_rel__simps_I39_J,axiom,
    ! [L] : pls != bit1(L) ).

fof(fact_68_rel__simps_I50_J,axiom,
    ! [K,L] : bit1(K) != bit0(L) ).

fof(fact_69_rel__simps_I49_J,axiom,
    ! [K,L] : bit0(K) != bit1(L) ).

fof(fact_70_rel__simps_I44_J,axiom,
    ! [K_1] :
      ( bit0(K_1) = pls
    <=> K_1 = pls ) ).

fof(fact_71_rel__simps_I38_J,axiom,
    ! [L_1] :
      ( pls = bit0(L_1)
    <=> pls = L_1 ) ).

fof(fact_72_Bit0__Pls,axiom,
    bit0(pls) = pls ).

fof(fact_73_Pls__def,axiom,
    pls = zero_zero(int) ).

fof(fact_74_int__0__neq__1,axiom,
    zero_zero(int) != one_one(int) ).

fof(fact_75_add__Pls__right,axiom,
    ! [K] : plus_plus(int,K,pls) = K ).

fof(fact_76_add__Pls,axiom,
    ! [K] : plus_plus(int,pls,K) = K ).

fof(fact_77_add__Bit0__Bit0,axiom,
    ! [K,L] : plus_plus(int,bit0(K),bit0(L)) = bit0(plus_plus(int,K,L)) ).

fof(fact_78_Bit0__def,axiom,
    ! [K] : bit0(K) = plus_plus(int,K,K) ).

fof(fact_79_zadd__0__right,axiom,
    ! [Z] : plus_plus(int,Z,zero_zero(int)) = Z ).

fof(fact_80_zadd__0,axiom,
    ! [Z] : plus_plus(int,zero_zero(int),Z) = Z ).

fof(fact_81_semiring__numeral__0__eq__0,axiom,
    ! [X_a] :
      ( number_semiring(X_a)
     => number_number_of(X_a,pls) = zero_zero(X_a) ) ).

fof(fact_82_number__of__Pls,axiom,
    ! [X_a] :
      ( number_ring(X_a)
     => number_number_of(X_a,pls) = zero_zero(X_a) ) ).

fof(fact_83_semiring__norm_I112_J,axiom,
    ! [X_a] :
      ( number_ring(X_a)
     => zero_zero(X_a) = number_number_of(X_a,pls) ) ).

fof(fact_84_add__numeral__0,axiom,
    ! [X_a] :
      ( number_ring(X_a)
     => ! [A_1] : plus_plus(X_a,number_number_of(X_a,pls),A_1) = ti(X_a,A_1) ) ).

fof(fact_85_add__numeral__0__right,axiom,
    ! [X_a] :
      ( number_ring(X_a)
     => ! [A_1] : plus_plus(X_a,A_1,number_number_of(X_a,pls)) = ti(X_a,A_1) ) ).

fof(fact_86_power__eq__0__iff__number__of,axiom,
    ! [X_a] :
      ( ( power(X_a)
        & mult_zero(X_a)
        & no_zero_divisors(X_a)
        & zero_neq_one(X_a) )
     => ! [A_2,Wa] :
          ( power_power(X_a,A_2,number_number_of(nat,Wa)) = zero_zero(X_a)
        <=> ( ti(X_a,A_2) = zero_zero(X_a)
            & number_number_of(nat,Wa) != zero_zero(nat) ) ) ) ).

fof(fact_87_add__number__of__left,axiom,
    ! [X_a] :
      ( number_ring(X_a)
     => ! [V,W,Z] : plus_plus(X_a,number_number_of(X_a,V),plus_plus(X_a,number_number_of(X_a,W),Z)) = plus_plus(X_a,number_number_of(X_a,plus_plus(int,V,W)),Z) ) ).

fof(fact_88_add__number__of__eq,axiom,
    ! [X_a] :
      ( number_ring(X_a)
     => ! [V,W] : plus_plus(X_a,number_number_of(X_a,V),number_number_of(X_a,W)) = number_number_of(X_a,plus_plus(int,V,W)) ) ).

fof(fact_89_number__of__add,axiom,
    ! [X_a] :
      ( number_ring(X_a)
     => ! [V,W] : number_number_of(X_a,plus_plus(int,V,W)) = plus_plus(X_a,number_number_of(X_a,V),number_number_of(X_a,W)) ) ).

fof(fact_90_add__Bit1__Bit0,axiom,
    ! [K,L] : plus_plus(int,bit1(K),bit0(L)) = bit1(plus_plus(int,K,L)) ).

fof(fact_91_add__Bit0__Bit1,axiom,
    ! [K,L] : plus_plus(int,bit0(K),bit1(L)) = bit1(plus_plus(int,K,L)) ).

fof(fact_92_Bit1__def,axiom,
    ! [K] : bit1(K) = plus_plus(int,plus_plus(int,one_one(int),K),K) ).

fof(fact_93_odd__nonzero,axiom,
    ! [Z] : plus_plus(int,plus_plus(int,one_one(int),Z),Z) != zero_zero(int) ).

fof(fact_94_number__of__int,axiom,
    ! [X_a] :
      ( number_semiring(X_a)
     => ! [N] : number_number_of(X_a,semiring_1_of_nat(int,N)) = semiring_1_of_nat(X_a,N) ) ).

fof(fact_95_zero__less__power2,axiom,
    ! [X_a] :
      ( linordered_idom(X_a)
     => ! [A_2] :
          ( ord_less(X_a,zero_zero(X_a),power_power(X_a,A_2,number_number_of(nat,bit0(bit1(pls)))))
        <=> ti(X_a,A_2) != zero_zero(X_a) ) ) ).

fof(fact_96_power2__less__0,axiom,
    ! [X_a] :
      ( linordered_idom(X_a)
     => ! [A_1] : ~ ord_less(X_a,power_power(X_a,A_1,number_number_of(nat,bit0(bit1(pls)))),zero_zero(X_a)) ) ).

fof(fact_97_sum__power2__gt__zero__iff,axiom,
    ! [X_a] :
      ( linordered_idom(X_a)
     => ! [Xa,Ya] :
          ( ord_less(X_a,zero_zero(X_a),plus_plus(X_a,power_power(X_a,Xa,number_number_of(nat,bit0(bit1(pls)))),power_power(X_a,Ya,number_number_of(nat,bit0(bit1(pls))))))
        <=> ( ti(X_a,Xa) != zero_zero(X_a)
            | ti(X_a,Ya) != zero_zero(X_a) ) ) ) ).

%----Arities (21)
fof(arity_Int_Oint___Groups_Olinordered__ab__group__add,axiom,
    linord219039673up_add(int) ).

fof(arity_Int_Oint___Rings_Oring__1__no__zero__divisors,axiom,
    ring_11004092258visors(int) ).

fof(arity_Int_Oint___Rings_Ono__zero__divisors,axiom,
    no_zero_divisors(int) ).

fof(arity_Int_Oint___Rings_Olinordered__idom,axiom,
    linordered_idom(int) ).

fof(arity_Int_Oint___Int_Onumber__semiring,axiom,
    number_semiring(int) ).

fof(arity_Int_Oint___Rings_Ozero__neq__one,axiom,
    zero_neq_one(int) ).

fof(arity_Int_Oint___Rings_Osemiring__1,axiom,
    semiring_1(int) ).

fof(arity_Int_Oint___Rings_Osemiring__0,axiom,
    semiring_0(int) ).

fof(arity_Int_Oint___Rings_Omult__zero,axiom,
    mult_zero(int) ).

fof(arity_Int_Oint___Int_Oring__char__0,axiom,
    ring_char_0(int) ).

fof(arity_Int_Oint___Int_Onumber__ring,axiom,
    number_ring(int) ).

fof(arity_Int_Oint___Power_Opower,axiom,
    power(int) ).

fof(arity_Int_Oint___Int_Onumber,axiom,
    number(int) ).

fof(arity_Nat_Onat___Rings_Ono__zero__divisors,axiom,
    no_zero_divisors(nat) ).

fof(arity_Nat_Onat___Int_Onumber__semiring,axiom,
    number_semiring(nat) ).

fof(arity_Nat_Onat___Rings_Ozero__neq__one,axiom,
    zero_neq_one(nat) ).

fof(arity_Nat_Onat___Rings_Osemiring__1,axiom,
    semiring_1(nat) ).

fof(arity_Nat_Onat___Rings_Osemiring__0,axiom,
    semiring_0(nat) ).

fof(arity_Nat_Onat___Rings_Omult__zero,axiom,
    mult_zero(nat) ).

fof(arity_Nat_Onat___Power_Opower,axiom,
    power(nat) ).

fof(arity_Nat_Onat___Int_Onumber,axiom,
    number(nat) ).

%----Helper facts (1)
fof(help_ti_idem,axiom,
    ! [T,A] : ti(T,ti(T,A)) = ti(T,A) ).

%----Conjectures (1)
fof(conj_0,conjecture,
    power_power(int,plus_plus(int,one_one(int),semiring_1_of_nat(int,n)),number_number_of(nat,bit0(bit1(pls)))) != zero_zero(int) ).

%------------------------------------------------------------------------------
