%--------------------------------------------------------------------------
% File     : NLP002+1 : TPTP v8.1.2. Released v2.4.0.
% Domain   : Natural Language Processing
% Problem  : "The old dirty white Chevy" problem 2
% Version  : [Bos00] axioms.
% English  : A problem generated by the DORIS [Bos00] system when parsing
%            the statement "The old dirty white Chevy barrels down a lonely
%            street in Hollywood".

% Refs     : [Bos00] Bos (2000), DORIS: Discourse Oriented Representation an
%            [Bau99] Baumgartner 999), FTP'2000 - Problem Sets
% Source   : [Bau99]
% Names    :

% Status   : CounterSatisfiable
% Rating   : 0.00 v7.5.0, 0.20 v7.4.0, 0.00 v6.1.0, 0.09 v6.0.0, 0.00 v4.1.0, 0.20 v4.0.1, 0.00 v3.1.0, 0.17 v2.6.0, 0.00 v2.4.0
% Syntax   : Number of formulae    :   34 (   0 unt;   0 def)
%            Number of atoms       :   87 (   1 equ)
%            Maximal formula atoms :   14 (   2 avg)
%            Number of connectives :   63 (  10   ~;   0   |;  20   &)
%                                         (   2 <=>;  31  =>;   0  <=;   0 <~>)
%            Maximal formula depth :   19 (   4 avg)
%            Maximal term depth    :    1 (   1 avg)
%            Number of predicates  :   37 (  36 usr;   0 prp; 1-3 aty)
%            Number of functors    :    0 (   0 usr;   0 con; --- aty)
%            Number of variables   :   47 (  42   !;   5   ?)
% SPC      : FOF_CSA_RFO_SEQ

% Comments :
%--------------------------------------------------------------------------
fof(ax1,axiom,
    ! [U] :
      ( chevy(U)
     => car(U) ) ).

fof(ax2,axiom,
    ! [U] :
      ( car(U)
     => vehicle(U) ) ).

fof(ax3,axiom,
    ! [U] :
      ( vehicle(U)
     => transport(U) ) ).

fof(ax4,axiom,
    ! [U] :
      ( transport(U)
     => instrumentality(U) ) ).

fof(ax5,axiom,
    ! [U] :
      ( instrumentality(U)
     => artifact(U) ) ).

fof(ax6,axiom,
    ! [U] :
      ( instrumentality(U)
     => ~ way(U) ) ).

fof(ax7,axiom,
    ! [U] :
      ( street(U)
     => way(U) ) ).

fof(ax8,axiom,
    ! [U] :
      ( way(U)
     => artifact(U) ) ).

fof(ax9,axiom,
    ! [U] :
      ( artifact(U)
     => object(U) ) ).

fof(ax10,axiom,
    ! [U] :
      ( artifact(U)
     => ~ location(U) ) ).

fof(ax11,axiom,
    ! [U] :
      ( event(U)
     => eventuality(U) ) ).

fof(ax12,axiom,
    ! [U] :
      ( hollywood(U)
     => city(U) ) ).

fof(ax13,axiom,
    ! [U] :
      ( city(U)
     => location(U) ) ).

fof(ax14,axiom,
    ! [U] :
      ( location(U)
     => object(U) ) ).

fof(ax15,axiom,
    ! [U] :
      ( object(U)
     => entity(U) ) ).

fof(ax16,axiom,
    ! [U] :
      ( old(U)
     => ~ new(U) ) ).

fof(ax17,axiom,
    ! [U] :
      ( eventuality(U)
     => ~ entity(U) ) ).

fof(ax18,axiom,
    ! [U] :
      ( abstraction(U)
     => ~ entity(U) ) ).

fof(ax19,axiom,
    ! [U] :
      ( abstraction(U)
     => ~ eventuality(U) ) ).

fof(ax20,axiom,
    ! [U] :
      ( male(U)
     => ~ female(U) ) ).

fof(ax21,axiom,
    ! [U] :
      ( man(U)
     => ~ woman(U) ) ).

fof(ax22,axiom,
    ! [U] :
      ( man(U)
     => male(U) ) ).

fof(ax23,axiom,
    ! [U] :
      ( male(U)
     => human(U) ) ).

fof(ax24,axiom,
    ! [U] :
      ( female(U)
     => human(U) ) ).

fof(ax25,axiom,
    ! [U] :
      ( woman(U)
     => female(U) ) ).

fof(ax26,axiom,
    ! [U] :
      ( drs(U)
    <=> proposition(U) ) ).

fof(ax27,axiom,
    ! [U] :
      ( nonhuman(U)
     => entity(U) ) ).

fof(ax28,axiom,
    ! [U] :
      ( human(U)
     => ~ nonhuman(U) ) ).

fof(ax29,axiom,
    ! [U,V,W] :
      ( ( have(U,V,W)
        & human(V) )
    <=> ( owner(V)
        & of(V,W) ) ) ).

fof(ax30,axiom,
    ! [U,V,W] :
      ( ( have(U,V,W)
        & nonhuman(V)
        & nonhuman(W) )
     => partof(W,V) ) ).

fof(ax31,axiom,
    ! [U,V,W] :
      ( ( event(U)
        & have(U,V,W) )
     => of(V,W) ) ).

fof(ax32,axiom,
    ! [U,V] :
      ( of(V,U)
     => ? [W] :
          ( event(W)
          & have(W,U,V) ) ) ).

fof(ax33,axiom,
    ! [U,V,W] :
      ( ( partof(U,V)
        & partof(U,W) )
     => V = W ) ).

fof(co1,conjecture,
    ~ ? [U,V,W,X] :
        ( hollywood(U)
        & city(U)
        & event(V)
        & street(W)
        & way(W)
        & lonely(W)
        & chevy(X)
        & car(X)
        & white(X)
        & dirty(X)
        & old(X)
        & barrel(V,X)
        & down(V,W)
        & in(V,U) ) ).

%--------------------------------------------------------------------------
