name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.22.0'
      - run: go install golang.org/x/tools/cmd/goyacc@latest
      - run: cd src && make
