name: Build And Test

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: sudo apt-get install -y golang-golang-x-tools
      - run: cd src && make
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: sudo apt-get install -y golang-golang-x-tools
      - run: cd src && make
      - run: cd src && go test ./...