name: Build And Test

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: sudo apt-get install -y golang-golang-x-tools
      - run: cd src && make
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: sudo apt-get install -y golang-golang-x-tools
      - run: cd src && make
      - run: cd src && go test ./...
  Soundness-1:
    #needs: Test
    if: github.ref == 'refs/heads/dev/jro'
    uses: GoelandProver/Goeland/.github/workflows/setup-tptp.yml@dev/jro
    with:
      folder: soundness_test/problems_0_INCLUDE
  Soundness-2:
    needs: Test
    if: github.ref == 'refs/heads/dev/jro'
    uses: GoelandProver/Goeland/.github/workflows/setup-tptp.yml@dev/jro
    with:
      folder: soundness_test/problems_1_INCLUDE
  Soundness-3:
    needs: Test
    if: github.ref == 'refs/heads/dev/jro'
    uses: GoelandProver/Goeland/.github/workflows/setup-tptp.yml@dev/jro
    with:
      folder: soundness_test/problems_2_INCLUDE
  Soundness-4:
    needs: Test
    if: github.ref == 'refs/heads/dev/jro'
    uses: GoelandProver/Goeland/.github/workflows/setup-tptp.yml@dev/jro
    with:
      folder: soundness_test/problems_3_INCLUDE
  Soundness-5:
    needs: Test
    if: github.ref == 'refs/heads/dev/jro'
    uses: GoelandProver/Goeland/.github/workflows/setup-tptp.yml@dev/jro
    with:
      folder: soundness_test/problems_4_INCLUDE
  Soundness-6:
    needs: Test
    if: github.ref == 'refs/heads/dev/jro'
    uses: GoelandProver/Goeland/.github/workflows/setup-tptp.yml@dev/jro
    with:
      folder: soundness_test/problems_5_INCLUDE
  Soundness-7:
    needs: Test
    if: github.ref == 'refs/heads/dev/jro'
    uses: GoelandProver/Goeland/.github/workflows/setup-tptp.yml@dev/jro
    with:
      folder: soundness_test/problems_6_INCLUDE