name: Full CI

on:
  pull_request:
    types: [labeled]

env:
  goVersion: '>=1.22.0'
  GOMEMLIMIT: '2750MiB'
  GOMAXPROCS: '3'

jobs:
  UnitTests:
    if: github.event.label.name == 'request:ci'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.22.0'
      - run: go install golang.org/x/tools/cmd/goyacc@latest
      - run: cd src && make && make tests

  VanillaSoundness:
    if: github.event.label.name == 'request:ci'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.goVersion }}
      - run: go install golang.org/x/tools/cmd/goyacc@latest
      - run: cd src && make
      - run: cd devtools && python3 run_soundness_tests.py ../.github/soundness 120

  InnerSoundness:
    if: github.event.label.name == 'request:ci'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.goVersion }}
      - run: go install golang.org/x/tools/cmd/goyacc@latest
      - run: cd src && make
      - run: cd devtools && python3 run_soundness_tests.py ../.github/soundness 120 -inner

  PreInnerSoundness:
    if: github.event.label.name == 'request:ci'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.goVersion }}
      - run: go install golang.org/x/tools/cmd/goyacc@latest
      - run: cd src && make
      - run: cd devtools && python3 run_soundness_tests.py ../.github/soundness 120 -preinner

  DMTSoundness:
    if: github.event.label.name == 'request:ci'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.goVersion }}
      - run: go install golang.org/x/tools/cmd/goyacc@latest
      - run: cd src && make
      - run: cd devtools && python3 run_soundness_tests.py ../.github/soundness 120 -dmt

  TestSuite:
    if: github.event.label.name == 'request:ci'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.goVersion }}
      - run: go install golang.org/x/tools/cmd/goyacc@latest
      - run: |
          bash -c "sh <(curl -fsSL https://opam.ocaml.org/install.sh)"
          opam init
          eval $(opam env)
          opam pin add rocq-prover 9.0.0
      - run: cd src && make
      - run: cd devtools && make test-suite
