name: Test On The Theorems Of The SET Category With CASC Settings

on: 
  workflow_call:
    inputs:
      folder:
        required: true
        type: string

jobs:
  SET-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: sudo apt-get install -y golang-golang-x-tools
      - run: cd src && make
      - run: wget https://tptp.org/TPTP/Distribution/TPTP-v8.1.0.tgz
      - run: tar -zxf TPTP-v8.1.0.tgz
      - run: rm TPTP-v8.1.0.tgz
      - run: mkdir SET_test
      - run: mv TPTP-v8.1.0/Axioms SET_test
      - run: python3 external_scripts/fof_tff_theorem.py SET TPTP-v8.1.0 SET_test/problems
      - run: python3 external_scripts/add_include.py ${{ inputs.folder }}/
      - run: rm -rf TPTP-v8.1.0
      - run: python3 external_scripts/run_theorem_test.py ${{ inputs.folder }}_INCLUDE 120  