name: Soundness Test With CASC Settings

on: 
  workflow_call:
    inputs:
      folder:
        required: true
        type: string

jobs:
  Soundness-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: sudo apt-get install -y golang-golang-x-tools
      - run: cd src && make
      - run: wget https://tptp.org/TPTP/Distribution/TPTP-v8.1.2.tgz
      - run: tar -zxf TPTP-v8.1.0.tgz
      - run: rm TPTP-v8.1.0.tgz
      - run: mkdir soundness_test
      - run: mv TPTP-v8.1.0/Axioms soundness_test
      - run: python3 external_scripts/fof_tff_countersat.py TPTP-v8.1.0 soundness_test/problems
      - run: python3 external_scripts/add_include.py ${{ inputs.folder }}/
      - run: rm -rf TPTP-v8.1.0
      - run: python3 external_scripts/run_soundness_test.py ${{ inputs.folder }}_INCLUDE 120