name: Soundness Test With CASC Settings

on: 
  push:
    branches:
      - 'dev/jro' # Put it back to develop when the testing environment is properly configured

jobs:
  Soundness-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: sudo apt-get install -y golang-golang-x-tools
      - run: cd src && make
      - run: wget https://tptp.org/TPTP/Distribution/TPTP-v8.1.0.tgz
      - run: tar -zxf TPTP-v8.1.0.tgz
      - run: rm TPTP-v8.1.0.tgz
      - run: mkdir soundness_test
      - run: mv TPTP-v8.1.0/Axioms soundness_test
      - run: python3 external_scripts/fof_tff_countersat.py TPTP-v8.1.0 soundness_test/problems
      - run: python3 external_scripts/add_include.py soundness_test/problems_0/
      - run: rm -rf TPTP-v8.1.0
      - run: python3 external_scripts/run_soundness_test.py soundness_test/problems_0_INCLUDE 120
      - run: rm -rf soundness_test
  Soundness-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: sudo apt-get install -y golang-golang-x-tools
      - run: cd src && make
      - run: wget https://tptp.org/TPTP/Distribution/TPTP-v8.1.0.tgz
      - run: tar -zxvf TPTP-v8.1.0.tgz
      - run: rm TPTP-v8.1.0.tgz
      - run: mkdir soundness_test
      - run: mv TPTP-v8.1.0/Axioms soundness_test
      - run: python3 external_scripts/fof_tff_countersat.py TPTP-v8.1.0 soundness_test/problems
      - run: python3 external_scripts/add_include.py soundness_test/problems_1/
      - run: rm -rf TPTP-v8.1.0
      - run: python3 external_scripts/run_soundness_test.py soundness_test/problems_1_INCLUDE 120
      - run: rm -rf soundness_test
  Soundness-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: sudo apt-get install -y golang-golang-x-tools
      - run: cd src && make
      - run: wget https://tptp.org/TPTP/Distribution/TPTP-v8.1.0.tgz
      - run: tar -zxvf TPTP-v8.1.0.tgz
      - run: rm TPTP-v8.1.0.tgz
      - run: mkdir soundness_test
      - run: mv TPTP-v8.1.0/Axioms soundness_test
      - run: python3 external_scripts/fof_tff_countersat.py TPTP-v8.1.0 soundness_test/problems
      - run: python3 external_scripts/add_include.py soundness_test/problems_2/
      - run: rm -rf TPTP-v8.1.0
      - run: python3 external_scripts/run_soundness_test.py soundness_test/problems_2_INCLUDE 120
      - run: rm -rf soundness_test
  Soundness-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: sudo apt-get install -y golang-golang-x-tools
      - run: cd src && make
      - run: wget https://tptp.org/TPTP/Distribution/TPTP-v8.1.0.tgz
      - run: tar -zxvf TPTP-v8.1.0.tgz
      - run: rm TPTP-v8.1.0.tgz
      - run: mkdir soundness_test
      - run: mv TPTP-v8.1.0/Axioms soundness_test
      - run: python3 external_scripts/fof_tff_countersat.py TPTP-v8.1.0 soundness_test/problems
      - run: python3 external_scripts/add_include.py soundness_test/problems_3/
      - run: rm -rf TPTP-v8.1.0
      - run: python3 external_scripts/run_soundness_test.py soundness_test/problems_3_INCLUDE 120
      - run: rm -rf soundness_test
  Soundness-5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: sudo apt-get install -y golang-golang-x-tools
      - run: cd src && make
      - run: wget https://tptp.org/TPTP/Distribution/TPTP-v8.1.0.tgz
      - run: tar -zxvf TPTP-v8.1.0.tgz
      - run: rm TPTP-v8.1.0.tgz
      - run: mkdir soundness_test
      - run: mv TPTP-v8.1.0/Axioms soundness_test
      - run: python3 external_scripts/fof_tff_countersat.py TPTP-v8.1.0 soundness_test/problems
      - run: python3 external_scripts/add_include.py soundness_test/problems_4/
      - run: rm -rf TPTP-v8.1.0
      - run: python3 external_scripts/run_soundness_test.py soundness_test/problems_4_INCLUDE 120
      - run: rm -rf soundness_test
  Soundness-6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: sudo apt-get install -y golang-golang-x-tools
      - run: cd src && make
      - run: wget https://tptp.org/TPTP/Distribution/TPTP-v8.1.0.tgz
      - run: tar -zxvf TPTP-v8.1.0.tgz
      - run: rm TPTP-v8.1.0.tgz
      - run: mkdir soundness_test
      - run: mv TPTP-v8.1.0/Axioms soundness_test
      - run: python3 external_scripts/fof_tff_countersat.py TPTP-v8.1.0 soundness_test/problems
      - run: python3 external_scripts/add_include.py soundness_test/problems_5/
      - run: rm -rf TPTP-v8.1.0
      - run: python3 external_scripts/run_soundness_test.py soundness_test/problems_5_INCLUDE 120
      - run: rm -rf soundness_test
  Soundness-7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: sudo apt-get install -y golang-golang-x-tools
      - run: cd src && make
      - run: wget https://tptp.org/TPTP/Distribution/TPTP-v8.1.0.tgz
      - run: tar -zxvf TPTP-v8.1.0.tgz
      - run: rm TPTP-v8.1.0.tgz
      - run: mkdir soundness_test
      - run: mv TPTP-v8.1.0/Axioms soundness_test
      - run: python3 external_scripts/fof_tff_countersat.py TPTP-v8.1.0 soundness_test/problems
      - run: python3 external_scripts/add_include.py soundness_test/problems_6/
      - run: rm -rf TPTP-v8.1.0
      - run: python3 external_scripts/run_soundness_test.py soundness_test/problems_6_INCLUDE 120
      - run: rm -rf soundness_test

      